# Generated by Django 4.1.5 on 2023-01-26 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_ord_no_comment_ordno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='ordno',
            new_name='order',
        ),
    ]
